---

- name: configure credentials
  tower_credential:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
    state: "{{ item.state }}"
    password: "{{ item.password }}"
    kind: 'Machine'
    # "{{ item.kind }}"
    tower_username: "{{ awx_username }}"
    tower_password: "{{ awx_password }}"
    tower_verify_ssl: "{{ awx_verify_ssl }}"
    tower_host: "{{ awx_host }}"
  register: awx_credentials
  ignore_errors: yes
  with_items: "{{ awx_credentials }}"

# tower_credential failed with errors so had to switch to command line
# fails with "Missing require fields: credential-type"

- name: create crdentials using tower-cli
  shell: "{{ lookup('template', 'awx_credentials.j2') }}"
  # no_log: yes
  register: awx_change_admin_password
  ignore_errors: yes
  with_items: "{{ awx_credentials }}"

- name: debug awx_change_admin_password
  debug:
    var: awx_change_admin_password
