---
#- name: configure credentials
#  tower_credential:
#    name: "{{ item.name }}"
#    description: "{{ item.description }}"
#    organization: "{{ item.organization }}"
#    state: "{{ item.state }}"
#    password: "{{ item.password }}"
#    kind: "ssh"
#    tower_username: "{{ awx_username }}"
#    tower_password: "{{ awx_password }}"
#    tower_verify_ssl: "{{ awx_verify_ssl }}"
#    tower_host: "{{ awx_host }}"
#  register: awx_credential_create
#  ignore_errors: yes
#  with_items: "{{ awx_credentials }}"

# tower_credential failed with errors so had to switch to command line
# fails with "Missing require fields: credential-type"

- name: set tower-cli config to avoid errors
  shell: 'tower-cli config verify_ssl false'

- name: create credentials using tower-cli
  shell: "{{ lookup('template', 'awx-credential.j2') }}"
  # no_log: yes
  register: awx_credential_shell
  ignore_errors: yes
  with_items: "{{ awx_credentials }}"

- name: create users using tower-cli
  shell: "{{ lookup('template', 'awx-user.j2') }}"
  # no_log: yes
  register: awx_user_shell
  ignore_errors: yes
  with_items: "{{ awx_users }}"

- name: create projects using tower-cli
  shell: "{{ lookup('template', 'awx-project.j2') }}"
  # no_log: yes
  register: awx_project_shell
  ignore_errors: yes
  # with_items: "{{ awx_projects }}"
  with_items:
    - "{{ awx_projects }}"

- name: create inventories using tower-cli
  shell: "{{ lookup('template', 'awx-inventory.j2') }}"
  # no_log: yes
  register: awx_inv_shell
  ignore_errors: yes
  # with_items: "{{ awx_projects }}"
  with_items:
    - "{{ awx_inventories }}"

- name: create hostss using tower-cli
  shell: "{{ lookup('template', 'awx-host.j2') }}"
  # no_log: yes
  register: awx_host_shell
  ignore_errors: yes
  # with_items: "{{ awx_projects }}"
  with_items:
    - "{{ awx_hosts }}"


- name: debug results
  debug:
    var: item
  ignore_errors: yes
  with_items:
    - "{{ awx_credential_shell }}"
    - "{{ awx_project_shell }}"
    - "{{ awx_user_shell }}"
    - "{{ awx_inv_shell }}"
    - "{{ awx_host_shell }}"

